######################################################################
# Automatically generated by qmake (2.01a) Sun May 6 13:56:50 2012
######################################################################

TEMPLATE = app
TARGET = kmlreader
QT += xml
DEPENDPATH += .
INCLUDEPATH += . /home/boris/marble_old/HEADER /home/boris/marble_old/src/lib
LIBS+= /home/boris/marble-build/src/lib/libmarblewidget.so
# Input
HEADERS += kmlreader.h kmlwriter.h
SOURCES += kmlreader.cpp kmlwriter.cpp main.cpp
